services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: chart-service-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: chart_service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "chart_service"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    container_name: chart-service-redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Chart Service Application
  app:
    build:
      context: .
      dockerfile: Containerfile
    container_name: chart-service-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: test.serwer.com
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chart_service
      DB_USER: postgres
      DB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRES_IN: 24h
      ALLOWED_ORIGINS: http://localhost:3000,http://localhost:3001
      LOG_LEVEL: info
      REDIS_URL: redis://redis:6379
      CHROMIUM_PATH: /usr/bin/chromium-browser
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    shm_size: 256m
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: chart-service-network